# See https://prettier.io/docs/en/configuration
trailingComma = "es5"
tabWidth = 4
semi = false
singleQuote = false

[[overrides]]
files = [ "*.json", "*.jsonc", "*.yml", "*.yaml" ]

  [overrides.options]
  tabWidth = 2
