[[worker]]
[worker.config]
id = "notetaker-mcp"

[worker.config.local_context]
user_id = "local-user"

[worker.config.local_context.metadata]
notes_dir = "./notes"
default_format = "markdown"

[worker.local]
packages = ["./toolkit"]