from arcade_google.models import SheetDataInput


def test_sheet_input_data_init():
    data = '{"1":{"A":"name","B":"age","C":"email","D":"score","E":"gender","F":"city","G":"country","H":"registration_date"},"2":{"A":"John Doe","B":28,"C":"johndoe@example.com","D":85,"E":"Male","F":"New York","G":"USA","H":"2023-01-15"},"3":{"A":"Jane Smith","B":34,"C":"janesmith@example.com","D":92,"E":"Female","F":"Los Angeles","G":"USA","H":"2023-02-20"},"4":{"A":"Alice Johnson","B":22,"C":"alicej@example.com","D":78,"E":"Female","F":"Chicago","G":"USA","H":"2023-03-10"},"5":{"A":"Bob Brown","B":45,"C":"bobbrown@example.com","D":88,"E":"Male","F":"Houston","G":"USA","H":"2023-04-05"},"6":{"A":"Charlie Davis","B":30,"C":"charlied@example.com","D":95,"E":"Male","F":"Phoenix","G":"USA","H":"2023-05-12"},"7":{"A":"Eve White","B":27,"C":"evewhite@example.com","D":82,"E":"Female","F":"Philadelphia","G":"USA","H":"2023-06-18"},"8":{"A":"Frank Black","B":40,"C":"frankb@example.com","D":90,"E":"Male","F":"San Antonio","G":"USA","H":"2023-07-25"},"9":{"A":"Grace Green","B":29,"C":"graceg@example.com","D":76,"E":"Female","F":"Dallas","G":"USA","H":"2023-08-30"},"10":{"A":"Hank Blue","B":35,"C":"hankb@example.com","D":89,"E":"Male","F":"San Diego","G":"USA","H":"2023-09-15"},"11":{"A":"Ivy Red","B":31,"C":"ivyred@example.com","D":91,"E":"Female","F":"San Jose","G":"USA","H":"2023-10-01"},"12":{"A":"Michael Grey","B":33,"C":"michaelg@example.com","D":87,"E":"Male","F":"Seattle","G":"USA","H":"2023-10-05"},"13":{"A":"Nina Black","B":26,"C":"ninab@example.com","D":84,"E":"Female","F":"Miami","G":"USA","H":"2023-10-10"},"14":{"A":"Oscar White","B":38,"C":"oscarw@example.com","D":90,"E":"Male","F":"Atlanta","G":"USA","H":"2023-10-15"},"15":{"A":"Paula Green","B":32,"C":"paulag@example.com","D":93,"E":"Female","F":"Boston","G":"USA","H":"2023-10-20"},"16":{"A":"Quentin Brown","B":29,"C":"quentinb@example.com","D":81,"E":"Male","F":"Denver","G":"USA","H":"2023-10-25"},"17":{"A":"Rachel Blue","B":24,"C":"rachelb@example.com","D":79,"E":"Female","F":"Orlando","G":"USA","H":"2023-10-30"},"18":{"A":"Steve Red","B":36,"C":"stever@example.com","D":88,"E":"Male","F":"Las Vegas","G":"USA","H":"2023-11-01"},"19":{"A":"Tina Yellow","B":30,"C":"tinay@example.com","D":85,"E":"Female","F":"Portland","G":"USA","H":"2023-11-05"},"20":{"A":"Ursula Pink","B":27,"C":"ursulap@example.com","D":82,"E":"Female","F":"San Francisco","G":"USA","H":"2023-11-10"},"21":{"A":"Victor Grey","B":41,"C":"victorg@example.com","D":91,"E":"Male","F":"Charlotte","G":"USA","H":"2023-11-15"},"22":{"A":"Wendy Black","B":34,"C":"wendyb@example.com","D":89,"E":"Female","F":"Detroit","G":"USA","H":"2023-11-20"},"23":{"A":"Xander White","B":29,"C":"xanderw@example.com","D":86,"E":"Male","F":"Indianapolis","G":"USA","H":"2023-11-25"},"24":{"A":"Yvonne Green","B":25,"C":"yvonnag@example.com","D":83,"E":"Female","F":"Columbus","G":"USA","H":"2023-11-30"},"25":{"A":"Zachary Blue","B":37,"C":"zacharyb@example.com","D":90,"E":"Male","F":"Jacksonville","G":"USA","H":"2023-12-01"},"26":{"A":"Alice Brown","B":28,"C":"aliceb@example.com","D":80,"E":"Female","F":"Memphis","G":"USA","H":"2023-12-05"},"27":{"A":"Brian Black","B":39,"C":"brianb@example.com","D":92,"E":"Male","F":"Nashville","G":"USA","H":"2023-12-10"},"28":{"A":"Cathy Green","B":31,"C":"cathyg@example.com","D":84,"E":"Female","F":"Virginia Beach","G":"USA","H":"2023-12-15"},"29":{"A":"DanielWhite","B":30,"C":"danielw@example.com","D":88,"E":"Male","F":"Atlanta","G":"USA","H":"2023-12-20"},"30":{"A":"Eva Red","B":26,"C":"evar@example.com","D":81,"E":"Female","F":"New Orleans","G":"USA","H":"2023-12-25"},"31":{"A":"Frankie Grey","B":35,"C":"frankieg@example.com","D":90,"E":"Male","F":"San Antonio","G":"USA","H":"2023-12-30"},"32":{"A":"Gina Blue","B":29,"C":"ginab@example.com","D":87,"E":"Female","F":"San Diego","G":"USA","H":"2024-01-01"},"33":{"A":"Henry Black","B":42,"C":"henryb@example.com","D":93,"E":"Male","F":"Philadelphia","G":"USA","H":"2024-01-05"},"34":{"A":"Isla Green","B":24,"C":"islag@example.com","D":79,"E":"Female","F":"Chicago","G":"USA","H":"2024-01-10"},"35":{"A":"Jack White","B":33,"C":"jackw@example.com","D":85,"E":"Male","F":"Los Angeles","G":"USA","H":"2024-01-15"},"36":{"A":"Kathy Red","B":31,"C":"kathyr@example.com","D":82,"E":"Female","F":"Miami","G":"USA","H":"2024-01-20"},"37":{"A":"Liam Grey","B":36,"C":"liamg@example.com","D":89,"E":"Male","F":"Seattle","G":"USA","H":"2024-01-25"},"38":{"A":"Mia Black","B":27,"C":"miab@example.com","D":80,"E":"Female","F":"Denver","G":"USA","H":"2024-01-30"},"39":{"A":"Nate Green","B":30,"C":"nateg@example.com","D":88,"E":"Male","F":"Orlando","G":"USA","H":"2024-02-01"},"43":{"A":100,"B":300,"C":234,"D":399,"E":5039,"F":2345,"G":23526,"H":123,"I":54,"J":234,"K":54,"L":23,"M":12,"N":57,"O":1324},"47":{"A":456,"B":234,"C":234,"D":399,"E":234,"F":1234,"G":23526,"H":123,"I":54,"J":234,"K":4567,"L":23,"M":12,"N":234,"O":1324}}'
    expected_data = {
        1: {
            "A": "name",
            "B": "age",
            "C": "email",
            "D": "score",
            "E": "gender",
            "F": "city",
            "G": "country",
            "H": "registration_date",
        },
        2: {
            "A": "John Doe",
            "B": 28,
            "C": "johndoe@example.com",
            "D": 85,
            "E": "Male",
            "F": "New York",
            "G": "USA",
            "H": "2023-01-15",
        },
        3: {
            "A": "Jane Smith",
            "B": 34,
            "C": "janesmith@example.com",
            "D": 92,
            "E": "Female",
            "F": "Los Angeles",
            "G": "USA",
            "H": "2023-02-20",
        },
        4: {
            "A": "Alice Johnson",
            "B": 22,
            "C": "alicej@example.com",
            "D": 78,
            "E": "Female",
            "F": "Chicago",
            "G": "USA",
            "H": "2023-03-10",
        },
        5: {
            "A": "Bob Brown",
            "B": 45,
            "C": "bobbrown@example.com",
            "D": 88,
            "E": "Male",
            "F": "Houston",
            "G": "USA",
            "H": "2023-04-05",
        },
        6: {
            "A": "Charlie Davis",
            "B": 30,
            "C": "charlied@example.com",
            "D": 95,
            "E": "Male",
            "F": "Phoenix",
            "G": "USA",
            "H": "2023-05-12",
        },
        7: {
            "A": "Eve White",
            "B": 27,
            "C": "evewhite@example.com",
            "D": 82,
            "E": "Female",
            "F": "Philadelphia",
            "G": "USA",
            "H": "2023-06-18",
        },
        8: {
            "A": "Frank Black",
            "B": 40,
            "C": "frankb@example.com",
            "D": 90,
            "E": "Male",
            "F": "San Antonio",
            "G": "USA",
            "H": "2023-07-25",
        },
        9: {
            "A": "Grace Green",
            "B": 29,
            "C": "graceg@example.com",
            "D": 76,
            "E": "Female",
            "F": "Dallas",
            "G": "USA",
            "H": "2023-08-30",
        },
        10: {
            "A": "Hank Blue",
            "B": 35,
            "C": "hankb@example.com",
            "D": 89,
            "E": "Male",
            "F": "San Diego",
            "G": "USA",
            "H": "2023-09-15",
        },
        11: {
            "A": "Ivy Red",
            "B": 31,
            "C": "ivyred@example.com",
            "D": 91,
            "E": "Female",
            "F": "San Jose",
            "G": "USA",
            "H": "2023-10-01",
        },
        12: {
            "A": "Michael Grey",
            "B": 33,
            "C": "michaelg@example.com",
            "D": 87,
            "E": "Male",
            "F": "Seattle",
            "G": "USA",
            "H": "2023-10-05",
        },
        13: {
            "A": "Nina Black",
            "B": 26,
            "C": "ninab@example.com",
            "D": 84,
            "E": "Female",
            "F": "Miami",
            "G": "USA",
            "H": "2023-10-10",
        },
        14: {
            "A": "Oscar White",
            "B": 38,
            "C": "oscarw@example.com",
            "D": 90,
            "E": "Male",
            "F": "Atlanta",
            "G": "USA",
            "H": "2023-10-15",
        },
        15: {
            "A": "Paula Green",
            "B": 32,
            "C": "paulag@example.com",
            "D": 93,
            "E": "Female",
            "F": "Boston",
            "G": "USA",
            "H": "2023-10-20",
        },
        16: {
            "A": "Quentin Brown",
            "B": 29,
            "C": "quentinb@example.com",
            "D": 81,
            "E": "Male",
            "F": "Denver",
            "G": "USA",
            "H": "2023-10-25",
        },
        17: {
            "A": "Rachel Blue",
            "B": 24,
            "C": "rachelb@example.com",
            "D": 79,
            "E": "Female",
            "F": "Orlando",
            "G": "USA",
            "H": "2023-10-30",
        },
        18: {
            "A": "Steve Red",
            "B": 36,
            "C": "stever@example.com",
            "D": 88,
            "E": "Male",
            "F": "Las Vegas",
            "G": "USA",
            "H": "2023-11-01",
        },
        19: {
            "A": "Tina Yellow",
            "B": 30,
            "C": "tinay@example.com",
            "D": 85,
            "E": "Female",
            "F": "Portland",
            "G": "USA",
            "H": "2023-11-05",
        },
        20: {
            "A": "Ursula Pink",
            "B": 27,
            "C": "ursulap@example.com",
            "D": 82,
            "E": "Female",
            "F": "San Francisco",
            "G": "USA",
            "H": "2023-11-10",
        },
        21: {
            "A": "Victor Grey",
            "B": 41,
            "C": "victorg@example.com",
            "D": 91,
            "E": "Male",
            "F": "Charlotte",
            "G": "USA",
            "H": "2023-11-15",
        },
        22: {
            "A": "Wendy Black",
            "B": 34,
            "C": "wendyb@example.com",
            "D": 89,
            "E": "Female",
            "F": "Detroit",
            "G": "USA",
            "H": "2023-11-20",
        },
        23: {
            "A": "Xander White",
            "B": 29,
            "C": "xanderw@example.com",
            "D": 86,
            "E": "Male",
            "F": "Indianapolis",
            "G": "USA",
            "H": "2023-11-25",
        },
        24: {
            "A": "Yvonne Green",
            "B": 25,
            "C": "yvonnag@example.com",
            "D": 83,
            "E": "Female",
            "F": "Columbus",
            "G": "USA",
            "H": "2023-11-30",
        },
        25: {
            "A": "Zachary Blue",
            "B": 37,
            "C": "zacharyb@example.com",
            "D": 90,
            "E": "Male",
            "F": "Jacksonville",
            "G": "USA",
            "H": "2023-12-01",
        },
        26: {
            "A": "Alice Brown",
            "B": 28,
            "C": "aliceb@example.com",
            "D": 80,
            "E": "Female",
            "F": "Memphis",
            "G": "USA",
            "H": "2023-12-05",
        },
        27: {
            "A": "Brian Black",
            "B": 39,
            "C": "brianb@example.com",
            "D": 92,
            "E": "Male",
            "F": "Nashville",
            "G": "USA",
            "H": "2023-12-10",
        },
        28: {
            "A": "Cathy Green",
            "B": 31,
            "C": "cathyg@example.com",
            "D": 84,
            "E": "Female",
            "F": "Virginia Beach",
            "G": "USA",
            "H": "2023-12-15",
        },
        29: {
            "A": "DanielWhite",
            "B": 30,
            "C": "danielw@example.com",
            "D": 88,
            "E": "Male",
            "F": "Atlanta",
            "G": "USA",
            "H": "2023-12-20",
        },
        30: {
            "A": "Eva Red",
            "B": 26,
            "C": "evar@example.com",
            "D": 81,
            "E": "Female",
            "F": "New Orleans",
            "G": "USA",
            "H": "2023-12-25",
        },
        31: {
            "A": "Frankie Grey",
            "B": 35,
            "C": "frankieg@example.com",
            "D": 90,
            "E": "Male",
            "F": "San Antonio",
            "G": "USA",
            "H": "2023-12-30",
        },
        32: {
            "A": "Gina Blue",
            "B": 29,
            "C": "ginab@example.com",
            "D": 87,
            "E": "Female",
            "F": "San Diego",
            "G": "USA",
            "H": "2024-01-01",
        },
        33: {
            "A": "Henry Black",
            "B": 42,
            "C": "henryb@example.com",
            "D": 93,
            "E": "Male",
            "F": "Philadelphia",
            "G": "USA",
            "H": "2024-01-05",
        },
        34: {
            "A": "Isla Green",
            "B": 24,
            "C": "islag@example.com",
            "D": 79,
            "E": "Female",
            "F": "Chicago",
            "G": "USA",
            "H": "2024-01-10",
        },
        35: {
            "A": "Jack White",
            "B": 33,
            "C": "jackw@example.com",
            "D": 85,
            "E": "Male",
            "F": "Los Angeles",
            "G": "USA",
            "H": "2024-01-15",
        },
        36: {
            "A": "Kathy Red",
            "B": 31,
            "C": "kathyr@example.com",
            "D": 82,
            "E": "Female",
            "F": "Miami",
            "G": "USA",
            "H": "2024-01-20",
        },
        37: {
            "A": "Liam Grey",
            "B": 36,
            "C": "liamg@example.com",
            "D": 89,
            "E": "Male",
            "F": "Seattle",
            "G": "USA",
            "H": "2024-01-25",
        },
        38: {
            "A": "Mia Black",
            "B": 27,
            "C": "miab@example.com",
            "D": 80,
            "E": "Female",
            "F": "Denver",
            "G": "USA",
            "H": "2024-01-30",
        },
        39: {
            "A": "Nate Green",
            "B": 30,
            "C": "nateg@example.com",
            "D": 88,
            "E": "Male",
            "F": "Orlando",
            "G": "USA",
            "H": "2024-02-01",
        },
        43: {
            "A": 100,
            "B": 300,
            "C": 234,
            "D": 399,
            "E": 5039,
            "F": 2345,
            "G": 23526,
            "H": 123,
            "I": 54,
            "J": 234,
            "K": 54,
            "L": 23,
            "M": 12,
            "N": 57,
            "O": 1324,
        },
        47: {
            "A": 456,
            "B": 234,
            "C": 234,
            "D": 399,
            "E": 234,
            "F": 1234,
            "G": 23526,
            "H": 123,
            "I": 54,
            "J": 234,
            "K": 4567,
            "L": 23,
            "M": 12,
            "N": 234,
            "O": 1324,
        },
    }

    sheet_input_data = SheetDataInput(data=data)
    assert sheet_input_data.data == expected_data
