[pack]
name = "Nate's pack"
description = "Nate's example tools"
version = "0.1.0"
author = "Nate"
email = "nate@arcade-ai.com"

[depends]

[tools]
Add = "arithmetic.add@0.0.1"
Divide = "arithmetic.divide@0.0.1"
Sqrt = "arithmetic.sqrt@0.0.1"
