

[pack]
name = "example"
description = "A simple actor that sends an email using the Gmail API."
version = "0.1.0"
author = "Sam Partee"
email = "sam@partee.io"

[modules]
gmailer = "0.1.0"
chat = "0.1.0"
search = "0.1.0"
read_sqlite = "0.1.0"
