[pack]
name = "example"
description = "A simple actor that sends an email using the Gmail API."
version = "0.1.0"
author = "Sam Partee"
email = "sam@partee.io"

[depends]

[tools]
SendEmail = "gmailer.send_email@0.1.0"
ReadEmail = "gmailer.read_email@0.1.0"
PlotDataframe = "gmailer.plot_dataframe@0.1.0"
Summarize = "chat.summarize@0.1.0"
