[pack]
name = "Routines for Jarvis"
description = "Jarvis Chatbot routines"
version = "0.1.0"
author = "Sam Partee"
email = "sam@partee.io"

[depends]

[tools]
Summarize = "llm.summarize@0.0.1"
Respond = "llm.respond@0.0.1"
SendEmail = "gmail.send_email@0.0.1"
ReadEmail = "gmail.read_email@0.0.1"
