[[worker]]

[worker.config]
id = "zendesk-toolkit"
enabled = true
timeout = 30
retries = 3
secret = "arc_o1XC6pKamyLz4wET5veMWCdzWBR138vxEH9DFbKkw1pjDm4Mm6sW"

[worker.local_source]
packages = [ "./zendesk",]