[[worker]]

[worker.config]
id = "mcpnotes"
enabled = true
timeout = 10
retries = 3
secret = "dev"

[worker.config.local_context.metadata]
notes_dir = "./workspace"
default_format = "markdown"

[worker.local_source]
packages = ["."]
