name: Community Toolkits (Test)

on:
  push:
    branches:
      - dev/ericgustin/community-toolkits

env:
  PYTHON_VERSION: "3.11"

jobs:
  create-community-toolkit-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('arcade/poetry.lock') }}

      - name: Install dependencies and activate venv
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          cd arcade
          poetry install --no-interaction --all-extras
          VENV_PATH=$(poetry env info --path)
          source $VENV_PATH/bin/activate
          cd ..
        shell: bash

      - name: List installed packages
        run: |
          pip list
        shell: bash

      - name: Run script
        run: poetry run python community_toolkits/create_community_toolkit_docs.py
