name: Community Toolkits (Test)

on:
  push:
    branches:
      - dev/ericgustin/community-toolkits

jobs:
  create-community-toolkit-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Python and Poetry Environment
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: '3.10'

      - name: Run your script or action
        run: python community_toolkits/create_community_toolkit_docs.py
