name: Test LangChain Arcade

on:
  push:
    branches:
      - main
    paths:
      - "contrib/langchain/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "contrib/langchain/**"

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4


      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env
        with:
          python-version: "3.11"
          working-directory: contrib/langchain

      - name: Install
        run: cd contrib/langchain && make install && make check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up the environment
        uses: ./.github/actions/setup-uv-env
        with:
          python-version: ${{ matrix.python-version }}
          working-directory: contrib/langchain

      - name: Install dependencies
        run: cd contrib/langchain && make install

      - name: Test & Coverage
        run: |
          cd contrib/langchain && make test && make coverage

      - name: Upload coverage reports to Codecov with GitHub Action on Python 3.11
        uses: codecov/codecov-action@v4.0.1
        if: ${{ matrix.python-version == '3.11' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: contrib/langchain/coverage.xml
          flags: langchain
