name: Test LangChain Arcade

on:
  push:
    branches:
      - main
    paths:
      - "contrib/langchain/**"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "contrib/langchain/**"

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-langchain-${{ hashFiles('contrib/langchain/.pre-commit-config.yaml') }}

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env
        with:
          python-version: "3.10"
          working-directory: contrib/langchain

      - name: Install
        working-directory: contrib/langchain
        run: make install

      - name: Run checks
        working-directory: contrib/langchain
        run: make check

  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
      fail-fast: false
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5

      - name: Load cached venv
        uses: actions/cache@v4
        with:
          path: contrib/langchain/.tox
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('contrib/langchain/poetry.lock') }}

      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Test with tox
        working-directory: contrib/langchain
        run: tox

      - name: Upload coverage reports to Codecov with GitHub Action on Python 3.11
        uses: codecov/codecov-action@v4.0.1
        if: ${{ matrix.python-version == '3.11' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: contrib/langchain/coverage.xml
          flags: langchain
